apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-hello
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: spring-hello=tnhmar/spring-hello-app
    argocd-image-updater.argoproj.io/spring-hello.update-strategy: latest
    argocd-image-updater.argoproj.io/spring-hello.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/spring-hello.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/spring-hello.allow-tags: regexp:^1\.0\.0-[0-9a-f]{12}$
    argocd-image-updater.argoproj.io/spring-hello.pull-secret: dockerhub
    argocd-image-updater.argoproj.io/write-back-method: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/tnhmar/devops-config
    targetRevision: HEAD
    path: helm/spring-hello
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
