apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-hello
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: tnhmar/spring-hello-app
    argocd-image-updater.argoproj.io/tnhmar_spring-hello-app.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/spring-hello.values: image.digest
    argocd-image-updater.argoproj.io/spring-hello.allow-tags: .*

spec:
  project: default
  source:
    repoURL: https://github.com/tnhmar/devops-config
    targetRevision: HEAD
    path: helm/spring-hello
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
