apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://registry.hub.docker.com": {
          "auth": "<username:password | base64>"
        }
      }
    }